# Generated by Django 5.2.2 on 2025-06-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id_buque', models.AutoField(db_column='id_buque', primary_key=True, serialize=False)),
                ('nombre_buque', models.CharField(db_column='nombre_buque', max_length=50)),
                ('matricula', models.CharField(db_column='matricula', max_length=10)),
                ('capacidad', models.FloatField(db_column='capacidad')),
            ],
            options={
                'verbose_name': 'Buque',
                'verbose_name_plural': 'Buques',
                'db_table': 'buque',
                'ordering': ['nombre_buque'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='nombre_categoria', max_length=20)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
                'db_table': 'categoria_producto',
                'ordering': ['nombre_categoria'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoViaje',
            fields=[
                ('id_estado', models.AutoField(db_column='id_estado', primary_key=True, serialize=False)),
                ('estado_viaje', models.CharField(db_column='estado_viaje', max_length=20)),
            ],
            options={
                'verbose_name': 'Estado del Viaje',
                'verbose_name_plural': 'Estados del Viaje',
                'db_table': 'estado_viaje',
                'ordering': ['id_estado'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(db_column='id_inventario', primary_key=True, serialize=False)),
                ('nivel_minimo', models.IntegerField(db_column='nivel_minimo')),
                ('cantidad_disponible', models.IntegerField(db_column='cantidad_disponible')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id_viaje', 'id_producto'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(db_column='nombre_producto', max_length=20)),
                ('url_foto', models.ImageField(blank=True, db_column='url_foto', null=True, upload_to='productos/')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre_producto'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoBuque',
            fields=[
                ('id_tipo', models.AutoField(db_column='id_tipo', primary_key=True, serialize=False)),
                ('tipo_buque', models.CharField(db_column='tipo_buque', max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Buque',
                'verbose_name_plural': 'Tipos de Buque',
                'db_table': 'tipo_buque',
                'ordering': ['tipo_buque'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad_medida', models.AutoField(db_column='id_unidad_medida', primary_key=True, serialize=False)),
                ('nombre_unidad_medida', models.CharField(db_column='nombre_unidad_medida', max_length=20)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidad_medida',
                'ordering': ['nombre_unidad_medida'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(db_column='id_viaje', primary_key=True, serialize=False)),
                ('codigo_viaje', models.IntegerField(db_column='codigo_viaje')),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('fecha_fin', models.DateField(db_column='fecha_fin')),
                ('destino', models.CharField(db_column='destino', max_length=50)),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'viaje',
                'ordering': ['fecha_inicio'],
                'managed': False,
            },
        ),
    ]
