# Generated by Django 5.2.2 on 2025-06-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'managed': True, 'ordering': ['nombre_categoria'], 'verbose_name': 'Categoría de Producto', 'verbose_name_plural': 'Categorías de Producto'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True, 'ordering': ['nombre_producto'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'managed': True, 'ordering': ['nombre_unidad_medida'], 'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
    ]
